import express from "express";
const router = express.Router();

// Fake dataset per-user
const USER_DATA = {
  user_123: {
    summary: {
      netPL: 1204.62,
      realizedPL: 970.18,
      unrealizedPL: 234.44,
      cashBalance: 9275.83,
      accountValue: 21602.91,
      buyingPower: 14860.3,
    },
    activity: [
      {
        id: "evt_1",
        timestamp: new Date().toISOString(),
        type: "TRADE",
        subtype: "BUY",
        symbol: "AAPL",
        quantity: 2,
        price: 191.2,
        amount: -382.4,
        fee: 0.25,
        status: "FILLED",
        notes: "Market order",
        orderId: "ord_77",
        transferId: null,
      },
      {
        id: "evt_2",
        timestamp: new Date(Date.now() - 3600_000).toISOString(),
        type: "TRANSFER",
        subtype: "DEPOSIT",
        symbol: null,
        quantity: null,
        price: null,
        amount: 500.0,
        fee: 0.0,
        status: "COMPLETED",
        notes: "ACH deposit",
        orderId: null,
        transferId: "tr_99",
      },
      {
        id: "evt_3",
        timestamp: new Date(Date.now() - 7200_000).toISOString(),
        type: "TRADE",
        subtype: "SELL",
        symbol: "TSLA",
        quantity: 1,
        price: 222.1,
        amount: 222.1,
        fee: 0.15,
        status: "FILLED",
        notes: "Limit order",
        orderId: "ord_88",
        transferId: null,
      },
      {
        id: "evt_4",
        timestamp: new Date(Date.now() - 9000_000).toISOString(),
        type: "FEE",
        subtype: null,
        symbol: null,
        quantity: null,
        price: null,
        amount: -0.25,
        fee: 0.0,
        status: "POSTED",
        notes: "SEC fee",
        orderId: null,
        transferId: null,
      },
      {
        id: "evt_5",
        timestamp: new Date(Date.now() - 14400_000).toISOString(),
        type: "TRADE",
        subtype: "BUY",
        symbol: "MSFT",
        quantity: 3,
        price: 415.6,
        amount: -1246.8,
        fee: 0.35,
        status: "FILLED",
        notes: "Limit order",
        orderId: "ord_80",
        transferId: null,
      },
      {
        id: "evt_6",
        timestamp: new Date(Date.now() - 21600_000).toISOString(),
        type: "TRADE",
        subtype: "SELL",
        symbol: "NVDA",
        quantity: 5,
        price: 134.5,
        amount: 672.5,
        fee: 0.3,
        status: "FILLED",
        notes: "Market order",
        orderId: "ord_81",
        transferId: null,
      },
      {
        id: "evt_7",
        timestamp: new Date(Date.now() - 32400_000).toISOString(),
        type: "TRANSFER",
        subtype: "DEPOSIT",
        symbol: null,
        quantity: null,
        price: null,
        amount: 2000.0,
        fee: 0.0,
        status: "COMPLETED",
        notes: "Wire transfer",
        orderId: null,
        transferId: "tr_100",
      },
      {
        id: "evt_8",
        timestamp: new Date(Date.now() - 43200_000).toISOString(),
        type: "TRADE",
        subtype: "BUY",
        symbol: "GOOGL",
        quantity: 4,
        price: 176.3,
        amount: -705.2,
        fee: 0.2,
        status: "FILLED",
        notes: "Market order",
        orderId: "ord_82",
        transferId: null,
      },
      {
        id: "evt_9",
        timestamp: new Date(Date.now() - 54000_000).toISOString(),
        type: "DIVIDEND",
        subtype: null,
        symbol: "AAPL",
        quantity: null,
        price: null,
        amount: 4.8,
        fee: 0.0,
        status: "POSTED",
        notes: "Quarterly dividend",
        orderId: null,
        transferId: null,
      },
      {
        id: "evt_10",
        timestamp: new Date(Date.now() - 64800_000).toISOString(),
        type: "TRADE",
        subtype: "SELL",
        symbol: "AMZN",
        quantity: 2,
        price: 185.9,
        amount: 371.8,
        fee: 0.2,
        status: "FILLED",
        notes: "Limit order",
        orderId: "ord_83",
        transferId: null,
      },
      {
        id: "evt_11",
        timestamp: new Date(Date.now() - 75600_000).toISOString(),
        type: "TRADE",
        subtype: "BUY",
        symbol: "META",
        quantity: 3,
        price: 502.4,
        amount: -1507.2,
        fee: 0.4,
        status: "FILLED",
        notes: "Market order",
        orderId: "ord_84",
        transferId: null,
      },
      {
        id: "evt_12",
        timestamp: new Date(Date.now() - 86400_000).toISOString(),
        type: "FEE",
        subtype: null,
        symbol: null,
        quantity: null,
        price: null,
        amount: -0.15,
        fee: 0.0,
        status: "POSTED",
        notes: "TAF fee",
        orderId: null,
        transferId: null,
      },
      {
        id: "evt_13",
        timestamp: new Date(Date.now() - 97200_000).toISOString(),
        type: "TRANSFER",
        subtype: "WITHDRAWAL",
        symbol: null,
        quantity: null,
        price: null,
        amount: -750.0,
        fee: 0.0,
        status: "COMPLETED",
        notes: "ACH withdrawal",
        orderId: null,
        transferId: "tr_101",
      },
      {
        id: "evt_14",
        timestamp: new Date(Date.now() - 108000_000).toISOString(),
        type: "TRADE",
        subtype: "BUY",
        symbol: "AMD",
        quantity: 10,
        price: 162.75,
        amount: -1627.5,
        fee: 0.5,
        status: "FILLED",
        notes: "Limit order",
        orderId: "ord_85",
        transferId: null,
      },
      {
        id: "evt_15",
        timestamp: new Date(Date.now() - 126000_000).toISOString(),
        type: "TRADE",
        subtype: "SELL",
        symbol: "MSFT",
        quantity: 2,
        price: 420.1,
        amount: 840.2,
        fee: 0.25,
        status: "FILLED",
        notes: "Market order",
        orderId: "ord_86",
        transferId: null,
      },
      {
        id: "evt_16",
        timestamp: new Date(Date.now() - 144000_000).toISOString(),
        type: "DIVIDEND",
        subtype: null,
        symbol: "MSFT",
        quantity: null,
        price: null,
        amount: 6.3,
        fee: 0.0,
        status: "POSTED",
        notes: "Quarterly dividend",
        orderId: null,
        transferId: null,
      },
      {
        id: "evt_17",
        timestamp: new Date(Date.now() - 162000_000).toISOString(),
        type: "TRADE",
        subtype: "BUY",
        symbol: "NFLX",
        quantity: 1,
        price: 895.2,
        amount: -895.2,
        fee: 0.3,
        status: "FILLED",
        notes: "Market order",
        orderId: "ord_87",
        transferId: null,
      },
      {
        id: "evt_18",
        timestamp: new Date(Date.now() - 180000_000).toISOString(),
        type: "TRANSFER",
        subtype: "DEPOSIT",
        symbol: null,
        quantity: null,
        price: null,
        amount: 5000.0,
        fee: 0.0,
        status: "COMPLETED",
        notes: "Initial deposit",
        orderId: null,
        transferId: "tr_98",
      },
      {
        id: "evt_19",
        timestamp: new Date(Date.now() - 198000_000).toISOString(),
        type: "TRADE",
        subtype: "SELL",
        symbol: "AMD",
        quantity: 5,
        price: 170.4,
        amount: 852.0,
        fee: 0.25,
        status: "FILLED",
        notes: "Limit order",
        orderId: "ord_89",
        transferId: null,
      },
      {
        id: "evt_20",
        timestamp: new Date(Date.now() - 216000_000).toISOString(),
        type: "TRADE",
        subtype: "BUY",
        symbol: "TSLA",
        quantity: 3,
        price: 210.5,
        amount: -631.5,
        fee: 0.35,
        status: "FILLED",
        notes: "Market order",
        orderId: "ord_90",
        transferId: null,
      },
      {
        id: "evt_21",
        timestamp: new Date(Date.now() - 234000_000).toISOString(),
        type: "FEE",
        subtype: null,
        symbol: null,
        quantity: null,
        price: null,
        amount: -0.1,
        fee: 0.0,
        status: "POSTED",
        notes: "SEC fee",
        orderId: null,
        transferId: null,
      },
      {
        id: "evt_22",
        timestamp: new Date(Date.now() - 252000_000).toISOString(),
        type: "TRADE",
        subtype: "BUY",
        symbol: "DIS",
        quantity: 8,
        price: 112.35,
        amount: -898.8,
        fee: 0.3,
        status: "FILLED",
        notes: "Limit order",
        orderId: "ord_91",
        transferId: null,
      },
      {
        id: "evt_23",
        timestamp: new Date(Date.now() - 288000_000).toISOString(),
        type: "TRADE",
        subtype: "SELL",
        symbol: "GOOGL",
        quantity: 2,
        price: 180.45,
        amount: 360.9,
        fee: 0.2,
        status: "FILLED",
        notes: "Market order",
        orderId: "ord_92",
        transferId: null,
      },
      {
        id: "evt_24",
        timestamp: new Date(Date.now() - 324000_000).toISOString(),
        type: "TRADE",
        subtype: "BUY",
        symbol: "AMZN",
        quantity: 2,
        price: 178.6,
        amount: -357.2,
        fee: 0.2,
        status: "PENDING",
        notes: "Limit order - awaiting fill",
        orderId: "ord_93",
        transferId: null,
      },
      {
        id: "evt_25",
        timestamp: new Date(Date.now() - 360000_000).toISOString(),
        type: "TRADE",
        subtype: "BUY",
        symbol: "INTC",
        quantity: 20,
        price: 31.45,
        amount: -629.0,
        fee: 0.3,
        status: "FILLED",
        notes: "Market order",
        orderId: "ord_94",
        transferId: null,
      },
      {
        id: "evt_26",
        timestamp: new Date(Date.now() - 396000_000).toISOString(),
        type: "TRADE",
        subtype: "SELL",
        symbol: "DIS",
        quantity: 4,
        price: 118.9,
        amount: 475.6,
        fee: 0.2,
        status: "FILLED",
        notes: "Limit order",
        orderId: "ord_95",
        transferId: null,
      },
      {
        id: "evt_27",
        timestamp: new Date(Date.now() - 432000_000).toISOString(),
        type: "TRANSFER",
        subtype: "DEPOSIT",
        symbol: null,
        quantity: null,
        price: null,
        amount: 3000.0,
        fee: 0.0,
        status: "COMPLETED",
        notes: "Wire transfer",
        orderId: null,
        transferId: "tr_102",
      },
      {
        id: "evt_28",
        timestamp: new Date(Date.now() - 468000_000).toISOString(),
        type: "DIVIDEND",
        subtype: null,
        symbol: "GOOGL",
        quantity: null,
        price: null,
        amount: 3.2,
        fee: 0.0,
        status: "POSTED",
        notes: "Quarterly dividend",
        orderId: null,
        transferId: null,
      },
      {
        id: "evt_29",
        timestamp: new Date(Date.now() - 504000_000).toISOString(),
        type: "TRADE",
        subtype: "BUY",
        symbol: "PYPL",
        quantity: 6,
        price: 68.35,
        amount: -410.1,
        fee: 0.25,
        status: "FILLED",
        notes: "Limit order",
        orderId: "ord_96",
        transferId: null,
      },
      {
        id: "evt_30",
        timestamp: new Date(Date.now() - 540000_000).toISOString(),
        type: "FEE",
        subtype: null,
        symbol: null,
        quantity: null,
        price: null,
        amount: -0.2,
        fee: 0.0,
        status: "POSTED",
        notes: "SEC fee",
        orderId: null,
        transferId: null,
      },
      {
        id: "evt_31",
        timestamp: new Date(Date.now() - 576000_000).toISOString(),
        type: "TRADE",
        subtype: "SELL",
        symbol: "NFLX",
        quantity: 1,
        price: 920.8,
        amount: 920.8,
        fee: 0.3,
        status: "FILLED",
        notes: "Market order",
        orderId: "ord_97",
        transferId: null,
      },
      {
        id: "evt_32",
        timestamp: new Date(Date.now() - 600000_000).toISOString(),
        type: "TRANSFER",
        subtype: "WITHDRAWAL",
        symbol: null,
        quantity: null,
        price: null,
        amount: -500.0,
        fee: 0.0,
        status: "COMPLETED",
        notes: "ACH withdrawal",
        orderId: null,
        transferId: "tr_103",
      },
    ],
  },
};

function getUser(req) {
  const id = req.user?.id;
  return USER_DATA[id];
}

router.get("/ledger/summary", (req, res) => {
  const user = getUser(req);
  if (!user) return res.status(401).json({ error: "Not logged in" });
  res.json(user.summary);
});

router.get("/ledger/activity", (req, res) => {
  const user = getUser(req);
  if (!user) return res.status(401).json({ error: "Not logged in" });

  let items = [...user.activity];

  const { type, status, symbol, startDate, endDate, page = 1, pageSize = 25 } = req.query;

  // Date filters
  if (startDate) {
    const start = new Date(startDate);
    items = items.filter((x) => new Date(x.timestamp) >= start);
  }
  if (endDate) {
    const end = new Date(endDate);
    items = items.filter((x) => new Date(x.timestamp) <= end);
  }

  // Filters
  if (type) items = items.filter((x) => x.type === type);
  if (status) items = items.filter((x) => (x.status || "").toUpperCase() === status.toUpperCase());
  if (symbol) items = items.filter((x) => (x.symbol || "").toUpperCase() === symbol.toUpperCase());

  // Sort newest first
  items.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp));

  // Pagination
  const p = Number(page);
  const ps = Number(pageSize);
  const totalItems = items.length;
  const totalPages = Math.max(1, Math.ceil(totalItems / ps));
  const startIdx = (p - 1) * ps;
  const paginated = items.slice(startIdx, startIdx + ps);

  res.json({
    items: paginated,
    page: p,
    pageSize: ps,
    totalItems,
    totalPages,
  });
});

router.get("/ledger/activity/:id", (req, res) => {
  const user = getUser(req);
  if (!user) return res.status(401).json({ error: "Not logged in" });

  const evt = user.activity.find((x) => x.id === req.params.id);
  if (!evt) return res.status(404).json({ error: "Not found" });

  // add extra detail fields like a real backend would
  const detail = {
    ...evt,
    filledQuantity: evt.quantity,
    avgFillPrice: evt.price,
    orderType: evt.type === "TRADE" ? "MARKET" : null,
    failureReason: null,
  };

  res.json(detail);
});

export default router;